version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/git/sitio/certs:/etc/nginx/certs:ro
      - /root/git/sitio/vhostd:/etc/nginx/vhost.d
      - /root/git/sitio/www:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /root/git/sitio/certs:/etc/nginx/certs:rw
      - /root/git/sitio/vhostd:/etc/nginx/vhost.d
      - /root/git/sitio/www:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /root/git/sitio/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=volpini.com.ar,www.volpini.com.ar
      - LETSENCRYPT_HOST=volpini.com.ar,www.volpini.com.ar
      - LETSENCRYPT_EMAIL=volpinibruno@gmail.com
